src/Entity/Sortie.php
<?php

namespace App\Entity;

use App\Repository\SortieRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: SortieRepository::class)]
class Sortie
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $dateSortie = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: '0')]
    private ?string $qtSortie = null;

    #[ORM\ManyToOne(inversedBy: 'sorties')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Produit $produit = null;

    #[ORM\ManyToOne(inversedBy: 'sorties')]
    private ?User $user = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: '0')]
    private ?string $prixUnit = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: '0')]
    private ?string $total = null;

    #[ORM\ManyToOne(inversedBy: 'sorties')]
    private ?Client $client = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $action = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $NomProduit = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateSortie(): ?\DateTimeInterface
    {
        return $this->dateSortie;
    }

    public function setDateSortie(\DateTimeInterface $dateSortie): self
    {
        $this->dateSortie = $dateSortie;

        return $this;
    }

    public function getQtSortie(): ?string
    {
        return $this->qtSortie;
    }

    public function setQtSortie(string $qtSortie): self
    {
        $this->qtSortie = $qtSortie;

        return $this;
    }

    public function getProduit(): ?Produit
    {
        return $this->produit;
    }

    public function setProduit(?Produit $produit): self
    {
        $this->produit = $produit;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getPrixUnit(): ?string
    {
        return $this->prixUnit;
    }

    public function setPrixUnit(string $prixUnit): self
    {
        $this->prixUnit = $prixUnit;

        return $this;
    }

    public function getTotal(): ?string
    {
        return $this->total;
    }

    public function setTotal(string $total): self
    {
        $this->total = $total;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getAction(): ?string
    {
        return $this->action;
    }

    public function setAction(?string $action): self
    {
        $this->action = $action;

        return $this;
    }

    public function getNomProduit(): ?string
    {
        return $this->NomProduit;
    }

    public function setNomProduit(?string $NomProduit): self
    {
        $this->NomProduit = $NomProduit;

        return $this;
    }
}

src/Form/EntreeType.php
<?php

namespace App\Form;

use App\Entity\Entree;
use App\Entity\Fournisseur;
use App\Entity\Produit;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EntreeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $libelle = "";
        $builder
            ->add('fournisseur', EntityType::class, array(
                'label' => false,
                'class' => Fournisseur::class,
                'placeholder' => 'Nom du fournisseur',
                'required' => false,
                'attr' => array('class' => 'form-control form-group'),
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('f')
                        ->orderBy('f.nom', 'ASC'); // Tri par ordre alphabétique sur la colonne 'nom'
                },
            ))
            ->add('produit',EntityType::class, array(
                'class' => Produit::class,
                'label' => false,
                'attr' => array(
                    'class' => 'form-control form-group',
                    ),
                'placeholder' => 'grossistes',
                'required' => false,
                'query_builder' => function(EntityRepository $er) use ($libelle) {
                    return $er->createQueryBuilder('p')
                        ->where('p.libelle LIKE :libelle')
                        ->setParameter('libelle', '%'.$libelle.'%')
                        ->orderBy('p.libelle', 'ASC');
                },
            ))

            ->add('qtEntree', TextType::class, array(
                'label' => false,
                'attr' => array(
                    'class' => 'form-control form-group',
                    'placeholder' => 'Quantite achetée'
                )
            ))
            ->add('prixUnit', TextType::class, array(
                'label' => false,
                'attr' => array(
                    'class' => 'form-control form-group',
                    'placeholder' => 'prix unitaire'
                )
            ))

            ->add('Valider', SubmitType::class, array(
                'attr' =>array('class' => 'btn btn-primary form-group')
            ))
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Entree::class,
        ]);
    }
}

src/Controller/EntreeController.php
<?php

namespace App\Controller;

use App\Entity\Client;
use App\Entity\Entree;
use App\Entity\Fournisseur;
use App\Entity\Produit;
use App\Form\EntreeType;
use App\Repository\ClientRepository;
use App\Repository\EntreeRepository;
use App\Repository\FournisseurRepository;
use App\Repository\ProduitRepository;
use App\Service\EntreeValidatorService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class EntreeController extends AbstractController
{
    #[Route('/entree/liste', name: 'entree_liste')]
    public function index(EntreeRepository $entre,ProduitRepository $detail,FournisseurRepository $fourni, Request $request): Response
    {
        $page = $request->query->getInt('page', 1); // current page number
        $limit = 10; // number of products to display per page
        $total = $entre->countAll();
        $offset = ($page - 1) * $limit;
        $entree = $entre->findAllOrderedByDate($limit, $offset);
        $produits = $detail->findAllOrderedByDate();
        $details = $detail->findAllDetail();
        $fournisseur = $fourni->findAll();
        return $this->render('entree/liste.html.twig', [
            'controller_name' => 'EntreeController',
            'entree'=>$entree,
            'produits' => $produits,
            'details' => $details,
            'fournisseur' => $fournisseur,
            'total' => $total,
            'page' => $page,
            'limit' => $limit,
        ]);
        return $this->render('entree/liste.html.twig');
    }

    #[Route('/entree/add', name: 'entree_add')]
    public function add(EntityManagerInterface $manager, Request $request, EntreeValidatorService $validatorService): Response
    {
        if ($request->isMethod('POST')) {
            // Get the data from the request
            $produitId = $request->request->get('produit_id');
            $detailId = $request->request->get('detail_id');
            $fournisseurId = $request->request->get('fournisseur_id');
            $qtEntree = $request->request->get('qt_sortie');
            $prixUnit = $request->request->get('prix_unit');
            if (!empty($produitId) && !empty($detailId)) {
                $this->addFlash('danger', 'produit et detail ne peuvent pas être remplis en même temps.');
                return $this->redirectToRoute('sortie_liste');
            }

            $validationErrors = $validatorService->validate([
                'produitId' => $produitId,
                'qtSortie' => $qtEntree,
                'prixUnit' => $prixUnit,
                'fournisseur_id' => $fournisseurId,
            ]);

            if (!empty($validationErrors)) {
                foreach ($validationErrors as $error) {
                    $this->addFlash('danger', $error);
                }
                return $this->redirectToRoute('sortie_liste');
            }

            if (!empty($detailId)){
                $entree = new Entree();
                $date = new \DateTime();
                $entree->setDateEntree($date);
                $entree->setQtEntree($qtEntree);
                $entree->setPrixUnit($prixUnit);
                if ($fournisseurId != null) {
                    $fournisseur = $manager->getRepository(Fournisseur::class)->find($fournisseurId);
                    $entree->setFournisseur($fournisseur);
                }

                $produit = $manager->getRepository(Produit::class)->find($detailId);
                if (!$produit) {
                    $this->addFlash('danger', 'detail not found.');
                    return $this->redirectToRoute('sortie_liste');
                }

                $qtStock = $produit->getQtStockDetail();
                if ($qtStock < $qtEntree) {
                    $this->addFlash('danger', 'La quantité en stock est insuffisante pour satisfaire la demande. Quantité stock : ' . $qtStock);
                }

                    $entree->setProduit($produit);
                    $entree->setNomProduit($produit->getNomProduitDetail());
                    $entree->setTotal($prixUnit * $qtEntree);
                    $user = $this->getUser();
                    $entree->setUser($user);

                    $manager->persist($entree);
                    $manager->flush();
                    // Mise à jour qtestock produit

                    $p = $manager->getRepository(Produit::class)->find($detailId);
                    $quantite = floatval($entree->getQtEntree());
                    $nombre = $p->getNombre();
                    $vendus = $p->getNbreVendu();
                    if ($quantite >= $nombre) {
                        $boxe = $quantite / $nombre;
                        $vendus = $boxe;
                        $dstock = $p->getQtStock() + $vendus;
                        $p->setQtStock($dstock);
                        $p->setNbreVendu($vendus);
                    }else{
                        $boxe = $quantite / $nombre;
                        $vendus = $boxe;
                        $dstock = $p->getQtStock() + $vendus;
                        $p->setQtStock($dstock);
                        $p->setNbreVendu($vendus);
                    }
                    $upd = $nombre * $p->getQtStock();
                    $produit->setQtStockDetail($upd);
                    $entree->setAction('detail');
                    $manager->persist($entree);
                    $manager->flush();

                    $this->addFlash('success', 'Le produit a été enregistré avec succès.');
                }
            }
            if (!empty($produitId)){
                $entree = new Entree();
                $date = new \DateTime();
                $entree->setDateEntree($date);
                $entree->setQtEntree($qtEntree);
                $entree->setPrixUnit($prixUnit);

                $produit = $manager->getRepository(Produit::class)->find($produitId);
                if (!$produit) {
                    $this->addFlash('danger', 'Produit not found.');
                    return $this->redirectToRoute('sortie_liste');
                }

                $qtStock = $produit->getQtStock();

                    $entree->setProduit($produit);
                    $entree->setNomProduit($produit->getLibelle());
                    $entree->setTotal($prixUnit * $qtEntree);
                    $user = $this->getUser();
                    $entree->setUser($user);
                    if ($fournisseurId != null) {
                        $fournisseur = $manager->getRepository(Fournisseur::class)->find($fournisseurId);
                        $entree->setFournisseur($fournisseur);
                    }

                    $manager->persist($entree);
                    $manager->flush();
                    // Mise à jour qtestock produit
                    $produit->setQtStock($qtStock + $qtEntree);
                    $produit->setTotal($produit->getPrixUnit() * $produit->getQtStock());
                    if ($produit->getNombre() != null){
                        $upd = $produit->getNombre() * $entree->getQtEntree();
                        $produit->setQtStockDetail($produit->getQtStockDetail() + $upd);
                    }

                    $manager->persist($produit);
                    $manager->flush();

                    $this->addFlash('success', 'Le produit a été enregistré avec succès.');
            }
        return $this->redirectToRoute('entree_liste');
    }

    #[Route('/entree/modifier/{id}', name: 'entrer_modifier')]
    public function modifier(EntityManagerInterface $manager,ProduitRepository $detail,FournisseurRepository $fourni, Request $request, EntreeRepository $entreeRepository, int $id): Response
    {
        $entree = $entreeRepository->find($id);
        if ($request->isMethod('POST')){

            $qtEntree = $request->request->get('qt_sortie');
            $prixUnit = $request->request->get('prix_unit');

            $entree->setQtEntree($qtEntree);
            $entree->setPrixUnit($prixUnit);
            $total = $entree->getQtEntree() * $entree->getPrixUnit();
            $entree->setTotal($total);
            $manager->flush();
            $this->addFlash('success', 'Modifiée avec succès.');
            return $this->redirectToRoute('entree_liste');
        }

        $fournisseur = $manager->getRepository(Fournisseur::class)->findAll();
        $produits = $manager->getRepository(Produit::class)->findAll();
        $details = $detail->findAllDetail();

        return $this->render('entree/editer.html.twig', [
            'entree' => $entree,
            'fournisseur' => $fournisseur,
            'produits' => $produits,
            'details' => $details,

        ]);
    }

    #[Route('/entree/delete/{id}', name: 'entrer_delete')]
    public function delete(Entree $entree, EntreeRepository $repository, EntityManagerInterface $manager){
        $repository->remove($entree,true);
        $p = $manager->getRepository(Produit::class)->find($entree->getProduit()->getId());
        if ($entree->getAction() == 'detail') {
            $quantite = floatval($entree->getQtEntree());
            $nombre = $p->getNombre();
            $vendus = $p->getNbreVendu();
            if ($quantite >= $nombre) {
                $boxe = $quantite / $nombre;
                $vendus = $boxe;
                $dstock = $p->getQtStock() - $vendus;
                $p->setQtStock($dstock);
                $p->setNbreVendu($vendus);
            }else{
                $boxe = $quantite / $nombre;
                $vendus = $boxe;
                $dstock = $p->getQtStock() - $vendus;
                $p->setQtStock($dstock);
                $p->setNbreVendu($vendus);
            }
            $upd = $nombre * $p->getQtStock();
            $p->setQtStockDetail($upd);

            $upddd = $dstock * $p->getPrixUnit();

templates/entree/editer.html.twig
{% extends 'accueil.html.twig' %}

{% block title %}Facture{% endblock %}

{% block body %}
    <div class="container col-md-6">
        <div class="card ">
            <div class="card-header">Mes produits</div>
            <div class="card-body">
                <form method="post" action="{{ path('entrer_modifier', {'id': entree.id}) }}">
                    <select class="form-control mb-2" name="client_id" id="client_id">
                        <option value="{{ entree.id }}">{{ entree.fournisseur }}</option>
                    </select>
                    {% if entree.action == "detail" %}
                        <select class="form-control mb-2" name="detail_id" id="detail_id">
                            <option value="{{ entree.id }}">{{ entree.nomProduit }}</option>
                        </select>
                    {% else %}
                        <select class="form-control mb-2" name="produit_id" id="produit_id">
                            <option value="{{ entree.id }}">{{ entree.nomProduit }}</option>
                        </select>
                    {% endif %}
                    <input class="form-control mb-2" type="text" id="qt_sortie" name="qt_sortie" value="{{ entree.qtEntree }}" required>
                    <input class="form-control mb-2" type="text" id="prix_unit" name="prix_unit" value="{{ entree.prixUnit }}" required>


                    <button class="form-control" type="submit">Enregistrer les modifications</button>
                </form>

            </div>
        </div>
    </div>

{% endblock %}

templates/entree/liste.html.twig
{% extends 'accueil.html.twig' %}

{% block title %}Gestion des entrees{% endblock %}

{% block body %}
    {% for message in app.session.flashBag.get('success') %}
        <div id="flash-message" class="alert alert-success">{{ message }}</div>
    {% endfor %}
    {% for message in app.session.flashBag.get('danger') %}
        <div id="flash-message" class="alert alert-danger">{{ message }}</div>
    {% endfor %}
    <div class="row">
        <div class="container col-md-8">
            <div class="card ">
                <div class="card-header">Liste des achats</div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <tr>
                                <th>Fournisseur</th>
                                <th>Produit</th>
                                <th>Qté</th>
                                <th>P.Unit</th>
                                <th>Montant</th>
                                <th>Date</th>
                                <th>Action</th>
                            </tr>
                            {% for e in entree %}
                                <tr>
                                    <th>{{ e.fournisseur }}</th>
                                    <th>{% if e.produit is not null %}
                                            {{ e.nomProduit }}
                                        {% endif %}</th>
                                    <th>{{ e.qtEntree }}</th>
                                    <th>{{ e.prixUnit | number_format(0, ',', ' ') }}</th>
                                    <th>{{ e.total | number_format(0, ',', ' ') }}</th>
                                    <th>{{ e.dateEntree|date('d/m/Y') }}</th>
                                    <td>
{#
                                        <a href="{{ path('entrer_modifier', {'id': e.id}) }}" ><i class="fa fa-edit"></i></a>
#}
                                        <a class="btn btn-danger btn-circle btn-sm" href="{{ path('entrer_delete', {'id': e.id}) }}" ><i class="fa fa-trash" aria-hidden="true" onclick="return confirm('Êtes-vous sûr de vouloir supprimer ce produit ?');"></i></a>
                                    </td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center">
                            {% if total > limit %}
                                {% set pages = (total / limit)|round(0, 'ceil') %}
                                {% for i in 1..pages %}
                                    {% if i == page %}
                                        <li class="page-item active" aria-current="page">
                                            <span class="page-link">{{ i }} <span class="sr-only">(current)</span></span>
                                        </li>
                                    {% else %}
                                        <li class="page-item"><a class="page-link" href="{{ path('entree_liste', {'page': i}) }}">{{ i }}</a></li>
                                    {% endif %}
                                {% endfor %}
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
        <div class="container col-md-4">
            <div class="card">
                <div class="card-header">Formulaire de gestion des produits</div>
                <div class="card-body">
                    <form method="post" action="{{ path('entree_add') }}">
                        <select class="form-control mb-3" name="fournisseur_id" id="fournisseur_id">
                            <option value="" selected disabled>Choisissez un fournisseur</option>
                            {% for f in fournisseur %}
                                <option value="{{ f.id }}">{{ f.nom }}</option>
                            {% endfor %}
                        </select>

                        <select class="form-control mb-3" name="produit_id" id="produit_id">
                            <option value="" selected disabled>Choisissez un produit</option>
                            {% for p in produits %}
                                <option value="{{ p.id }}">{{ p.libelle }}</option>
                            {% endfor %}
                        </select>

                        <select class="form-control mb-3" name="detail_id" id="detail_id">
                            <option value="" selected disabled>Choisissez un produit en détail</option>
                            {% for d in details %}
                                {% if d.nomProduitDetail is not null %}
                                    <option value="{{ d.id }}">{{ d.nomProduitDetail }}</option>
                                {% endif %}
                            {% endfor %}
                        </select>
                        <div>

                        </div>
                        <input class="form-control mb-3" type="text" id="qt_sortie" name="qt_sortie" placeholder="quantité" required>

                        <input class="form-control mb-2" type="text" id="prix_unit" name="prix_unit" placeholder="prix unitaire" required>

                        <button class="form-control btn-primary mt-1" type="submit">Enregistrer</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <script src="https://unpkg.com/axios@1.1.2/dist/axios.min.js"></script>
    <script>
        setTimeout(function() {
            var flashMessage = document.getElementById('flash-message');
            if (flashMessage !== null) {
                flashMessage.remove();
            }
        }, 10000);
    </script>

{% endblock %}